import {MigrationInterface, QueryRunner} from "typeorm";

export class Init1576076164359 implements MigrationInterface {
    name = 'Init1576076164359'

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "tag" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL)`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6a9775008add570dc3e5a0bab7" ON "tag" ("name") `, undefined);
        await queryRunner.query(`CREATE TABLE "image" ("id" varchar PRIMARY KEY NOT NULL, "title" varchar NOT NULL, "file" varchar NOT NULL, "description" varchar NOT NULL)`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_bf884fdcc2e1cd88956ea3c066" ON "image" ("title") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_e67a107bf5046cd5b2b025a812" ON "image" ("description") `, undefined);
        await queryRunner.query(`CREATE TABLE "outher" ("id" varchar PRIMARY KEY NOT NULL, "nickname" varchar NOT NULL, "userDbId" varchar)`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_0d4c67409aad8ab48a4a8a1279" ON "outher" ("nickname") `, undefined);
        await queryRunner.query(`CREATE TABLE "user" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "mcfPassword" varchar NOT NULL, "lastAuthTime" datetime NOT NULL)`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_065d4d8f3b5adb4a08841eae3c" ON "user" ("name") `, undefined);
        await queryRunner.query(`CREATE TABLE "relying_party" ("dbId" varchar PRIMARY KEY NOT NULL)`, undefined);
        await queryRunner.query(`CREATE TABLE "redirect_uri" ("id" varchar PRIMARY KEY NOT NULL, "uri" varchar NOT NULL, "rpDbId" varchar)`, undefined);
        await queryRunner.query(`CREATE TABLE "authorization_code" ("code" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "redirectUri" varchar NOT NULL, "nonce" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`CREATE TABLE "authorization_code_scope" ("id" varchar PRIMARY KEY NOT NULL, "codeCode" varchar, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`CREATE TABLE "auto_login" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "token" varchar NOT NULL, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11e0cdea32bcd84e5f2f104726" ON "auto_login" ("token") `, undefined);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "relyingPartyDbId" varchar, "userDbId" varchar, "token" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c31d0a2f38e6e99110df62ab0a" ON "refresh_token" ("token") `, undefined);
        await queryRunner.query(`CREATE TABLE "refresh_token_scope" ("id" varchar PRIMARY KEY NOT NULL, "tokenId" integer, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`CREATE TABLE "user_grant" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42278d1d5983f6a927d37fff92" ON "user_grant" ("userDbId", "rpDbId", "scope") `, undefined);
        await queryRunner.query(`CREATE TABLE "image_db_outhers_outher" ("imageId" varchar NOT NULL, "outherId" varchar NOT NULL, PRIMARY KEY ("imageId", "outherId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_312215618fce569457cdf1df1d" ON "image_db_outhers_outher" ("imageId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_19ee4893cf3ef1eff16d3bbf05" ON "image_db_outhers_outher" ("outherId") `, undefined);
        await queryRunner.query(`CREATE TABLE "image_db_tags_tag" ("imageId" varchar NOT NULL, "tagId" varchar NOT NULL, PRIMARY KEY ("imageId", "tagId"))`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_55fd3f0bc67773f4217ceab3fb" ON "image_db_tags_tag" ("imageId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_9a38a6b95e3425b72f164c6970" ON "image_db_tags_tag" ("tagId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_0d4c67409aad8ab48a4a8a1279"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_outher" ("id" varchar PRIMARY KEY NOT NULL, "nickname" varchar NOT NULL, "userDbId" varchar, CONSTRAINT "FK_6adbb578cf75cd925df5f9d09a5" FOREIGN KEY ("userDbId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_outher"("id", "nickname", "userDbId") SELECT "id", "nickname", "userDbId" FROM "outher"`, undefined);
        await queryRunner.query(`DROP TABLE "outher"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_outher" RENAME TO "outher"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_0d4c67409aad8ab48a4a8a1279" ON "outher" ("nickname") `, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_redirect_uri" ("id" varchar PRIMARY KEY NOT NULL, "uri" varchar NOT NULL, "rpDbId" varchar, CONSTRAINT "FK_f49f1892e5367e4dc09fb3979b0" FOREIGN KEY ("rpDbId") REFERENCES "relying_party" ("dbId") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_redirect_uri"("id", "uri", "rpDbId") SELECT "id", "uri", "rpDbId" FROM "redirect_uri"`, undefined);
        await queryRunner.query(`DROP TABLE "redirect_uri"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_redirect_uri" RENAME TO "redirect_uri"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_authorization_code" ("code" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "redirectUri" varchar NOT NULL, "nonce" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_6b56ad33c58e27de579a0bdc99e" FOREIGN KEY ("userDbId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_9f5b318f2fb474fdbc1e62e1b6c" FOREIGN KEY ("rpDbId") REFERENCES "relying_party" ("dbId") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_authorization_code"("code", "userDbId", "rpDbId", "redirectUri", "nonce", "createdAt") SELECT "code", "userDbId", "rpDbId", "redirectUri", "nonce", "createdAt" FROM "authorization_code"`, undefined);
        await queryRunner.query(`DROP TABLE "authorization_code"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_authorization_code" RENAME TO "authorization_code"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_authorization_code_scope" ("id" varchar PRIMARY KEY NOT NULL, "codeCode" varchar, "scope" varchar NOT NULL, CONSTRAINT "FK_b467e08a2f8eadd9001ea84603b" FOREIGN KEY ("codeCode") REFERENCES "authorization_code" ("code") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_authorization_code_scope"("id", "codeCode", "scope") SELECT "id", "codeCode", "scope" FROM "authorization_code_scope"`, undefined);
        await queryRunner.query(`DROP TABLE "authorization_code_scope"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_authorization_code_scope" RENAME TO "authorization_code_scope"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_11e0cdea32bcd84e5f2f104726"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_auto_login" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "token" varchar NOT NULL, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_e5ae13be9616495b8778f8cd9fb" FOREIGN KEY ("userDbId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_auto_login"("id", "userDbId", "token", "updatedAt") SELECT "id", "userDbId", "token", "updatedAt" FROM "auto_login"`, undefined);
        await queryRunner.query(`DROP TABLE "auto_login"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_auto_login" RENAME TO "auto_login"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11e0cdea32bcd84e5f2f104726" ON "auto_login" ("token") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c31d0a2f38e6e99110df62ab0a"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "relyingPartyDbId" varchar, "userDbId" varchar, "token" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_f5fc6944d151b6044c08afe86b7" FOREIGN KEY ("userDbId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_23690e8dd31e920bc81f37d0135" FOREIGN KEY ("relyingPartyDbId") REFERENCES "relying_party" ("dbId") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_refresh_token"("id", "relyingPartyDbId", "userDbId", "token", "createdAt") SELECT "id", "relyingPartyDbId", "userDbId", "token", "createdAt" FROM "refresh_token"`, undefined);
        await queryRunner.query(`DROP TABLE "refresh_token"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_token" RENAME TO "refresh_token"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c31d0a2f38e6e99110df62ab0a" ON "refresh_token" ("token") `, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_token_scope" ("id" varchar PRIMARY KEY NOT NULL, "tokenId" integer, "scope" varchar NOT NULL, CONSTRAINT "FK_16c31e8ec23211ba61cab66a806" FOREIGN KEY ("tokenId") REFERENCES "refresh_token" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_refresh_token_scope"("id", "tokenId", "scope") SELECT "id", "tokenId", "scope" FROM "refresh_token_scope"`, undefined);
        await queryRunner.query(`DROP TABLE "refresh_token_scope"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_token_scope" RENAME TO "refresh_token_scope"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_42278d1d5983f6a927d37fff92"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_user_grant" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "scope" varchar NOT NULL, CONSTRAINT "FK_c51a6eabdf9087f4f30a60f1eef" FOREIGN KEY ("userDbId") REFERENCES "user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_3476a765e22f9b70ed26ee90478" FOREIGN KEY ("rpDbId") REFERENCES "relying_party" ("dbId") ON DELETE NO ACTION ON UPDATE NO ACTION)`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_user_grant"("id", "userDbId", "rpDbId", "scope") SELECT "id", "userDbId", "rpDbId", "scope" FROM "user_grant"`, undefined);
        await queryRunner.query(`DROP TABLE "user_grant"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_user_grant" RENAME TO "user_grant"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42278d1d5983f6a927d37fff92" ON "user_grant" ("userDbId", "rpDbId", "scope") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_312215618fce569457cdf1df1d"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_19ee4893cf3ef1eff16d3bbf05"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_image_db_outhers_outher" ("imageId" varchar NOT NULL, "outherId" varchar NOT NULL, CONSTRAINT "FK_312215618fce569457cdf1df1d0" FOREIGN KEY ("imageId") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_19ee4893cf3ef1eff16d3bbf054" FOREIGN KEY ("outherId") REFERENCES "outher" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("imageId", "outherId"))`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_image_db_outhers_outher"("imageId", "outherId") SELECT "imageId", "outherId" FROM "image_db_outhers_outher"`, undefined);
        await queryRunner.query(`DROP TABLE "image_db_outhers_outher"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_image_db_outhers_outher" RENAME TO "image_db_outhers_outher"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_312215618fce569457cdf1df1d" ON "image_db_outhers_outher" ("imageId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_19ee4893cf3ef1eff16d3bbf05" ON "image_db_outhers_outher" ("outherId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_55fd3f0bc67773f4217ceab3fb"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_9a38a6b95e3425b72f164c6970"`, undefined);
        await queryRunner.query(`CREATE TABLE "temporary_image_db_tags_tag" ("imageId" varchar NOT NULL, "tagId" varchar NOT NULL, CONSTRAINT "FK_55fd3f0bc67773f4217ceab3fb3" FOREIGN KEY ("imageId") REFERENCES "image" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_9a38a6b95e3425b72f164c69708" FOREIGN KEY ("tagId") REFERENCES "tag" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("imageId", "tagId"))`, undefined);
        await queryRunner.query(`INSERT INTO "temporary_image_db_tags_tag"("imageId", "tagId") SELECT "imageId", "tagId" FROM "image_db_tags_tag"`, undefined);
        await queryRunner.query(`DROP TABLE "image_db_tags_tag"`, undefined);
        await queryRunner.query(`ALTER TABLE "temporary_image_db_tags_tag" RENAME TO "image_db_tags_tag"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_55fd3f0bc67773f4217ceab3fb" ON "image_db_tags_tag" ("imageId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_9a38a6b95e3425b72f164c6970" ON "image_db_tags_tag" ("tagId") `, undefined);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_9a38a6b95e3425b72f164c6970"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_55fd3f0bc67773f4217ceab3fb"`, undefined);
        await queryRunner.query(`ALTER TABLE "image_db_tags_tag" RENAME TO "temporary_image_db_tags_tag"`, undefined);
        await queryRunner.query(`CREATE TABLE "image_db_tags_tag" ("imageId" varchar NOT NULL, "tagId" varchar NOT NULL, PRIMARY KEY ("imageId", "tagId"))`, undefined);
        await queryRunner.query(`INSERT INTO "image_db_tags_tag"("imageId", "tagId") SELECT "imageId", "tagId" FROM "temporary_image_db_tags_tag"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_image_db_tags_tag"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_9a38a6b95e3425b72f164c6970" ON "image_db_tags_tag" ("tagId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_55fd3f0bc67773f4217ceab3fb" ON "image_db_tags_tag" ("imageId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_19ee4893cf3ef1eff16d3bbf05"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_312215618fce569457cdf1df1d"`, undefined);
        await queryRunner.query(`ALTER TABLE "image_db_outhers_outher" RENAME TO "temporary_image_db_outhers_outher"`, undefined);
        await queryRunner.query(`CREATE TABLE "image_db_outhers_outher" ("imageId" varchar NOT NULL, "outherId" varchar NOT NULL, PRIMARY KEY ("imageId", "outherId"))`, undefined);
        await queryRunner.query(`INSERT INTO "image_db_outhers_outher"("imageId", "outherId") SELECT "imageId", "outherId" FROM "temporary_image_db_outhers_outher"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_image_db_outhers_outher"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_19ee4893cf3ef1eff16d3bbf05" ON "image_db_outhers_outher" ("outherId") `, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_312215618fce569457cdf1df1d" ON "image_db_outhers_outher" ("imageId") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_42278d1d5983f6a927d37fff92"`, undefined);
        await queryRunner.query(`ALTER TABLE "user_grant" RENAME TO "temporary_user_grant"`, undefined);
        await queryRunner.query(`CREATE TABLE "user_grant" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "user_grant"("id", "userDbId", "rpDbId", "scope") SELECT "id", "userDbId", "rpDbId", "scope" FROM "temporary_user_grant"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_user_grant"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_42278d1d5983f6a927d37fff92" ON "user_grant" ("userDbId", "rpDbId", "scope") `, undefined);
        await queryRunner.query(`ALTER TABLE "refresh_token_scope" RENAME TO "temporary_refresh_token_scope"`, undefined);
        await queryRunner.query(`CREATE TABLE "refresh_token_scope" ("id" varchar PRIMARY KEY NOT NULL, "tokenId" integer, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "refresh_token_scope"("id", "tokenId", "scope") SELECT "id", "tokenId", "scope" FROM "temporary_refresh_token_scope"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_refresh_token_scope"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c31d0a2f38e6e99110df62ab0a"`, undefined);
        await queryRunner.query(`ALTER TABLE "refresh_token" RENAME TO "temporary_refresh_token"`, undefined);
        await queryRunner.query(`CREATE TABLE "refresh_token" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "relyingPartyDbId" varchar, "userDbId" varchar, "token" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`INSERT INTO "refresh_token"("id", "relyingPartyDbId", "userDbId", "token", "createdAt") SELECT "id", "relyingPartyDbId", "userDbId", "token", "createdAt" FROM "temporary_refresh_token"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_refresh_token"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c31d0a2f38e6e99110df62ab0a" ON "refresh_token" ("token") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_11e0cdea32bcd84e5f2f104726"`, undefined);
        await queryRunner.query(`ALTER TABLE "auto_login" RENAME TO "temporary_auto_login"`, undefined);
        await queryRunner.query(`CREATE TABLE "auto_login" ("id" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "token" varchar NOT NULL, "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`INSERT INTO "auto_login"("id", "userDbId", "token", "updatedAt") SELECT "id", "userDbId", "token", "updatedAt" FROM "temporary_auto_login"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_auto_login"`, undefined);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11e0cdea32bcd84e5f2f104726" ON "auto_login" ("token") `, undefined);
        await queryRunner.query(`ALTER TABLE "authorization_code_scope" RENAME TO "temporary_authorization_code_scope"`, undefined);
        await queryRunner.query(`CREATE TABLE "authorization_code_scope" ("id" varchar PRIMARY KEY NOT NULL, "codeCode" varchar, "scope" varchar NOT NULL)`, undefined);
        await queryRunner.query(`INSERT INTO "authorization_code_scope"("id", "codeCode", "scope") SELECT "id", "codeCode", "scope" FROM "temporary_authorization_code_scope"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_authorization_code_scope"`, undefined);
        await queryRunner.query(`ALTER TABLE "authorization_code" RENAME TO "temporary_authorization_code"`, undefined);
        await queryRunner.query(`CREATE TABLE "authorization_code" ("code" varchar PRIMARY KEY NOT NULL, "userDbId" varchar, "rpDbId" varchar, "redirectUri" varchar NOT NULL, "nonce" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`, undefined);
        await queryRunner.query(`INSERT INTO "authorization_code"("code", "userDbId", "rpDbId", "redirectUri", "nonce", "createdAt") SELECT "code", "userDbId", "rpDbId", "redirectUri", "nonce", "createdAt" FROM "temporary_authorization_code"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_authorization_code"`, undefined);
        await queryRunner.query(`ALTER TABLE "redirect_uri" RENAME TO "temporary_redirect_uri"`, undefined);
        await queryRunner.query(`CREATE TABLE "redirect_uri" ("id" varchar PRIMARY KEY NOT NULL, "uri" varchar NOT NULL, "rpDbId" varchar)`, undefined);
        await queryRunner.query(`INSERT INTO "redirect_uri"("id", "uri", "rpDbId") SELECT "id", "uri", "rpDbId" FROM "temporary_redirect_uri"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_redirect_uri"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_0d4c67409aad8ab48a4a8a1279"`, undefined);
        await queryRunner.query(`ALTER TABLE "outher" RENAME TO "temporary_outher"`, undefined);
        await queryRunner.query(`CREATE TABLE "outher" ("id" varchar PRIMARY KEY NOT NULL, "nickname" varchar NOT NULL, "userDbId" varchar)`, undefined);
        await queryRunner.query(`INSERT INTO "outher"("id", "nickname", "userDbId") SELECT "id", "nickname", "userDbId" FROM "temporary_outher"`, undefined);
        await queryRunner.query(`DROP TABLE "temporary_outher"`, undefined);
        await queryRunner.query(`CREATE INDEX "IDX_0d4c67409aad8ab48a4a8a1279" ON "outher" ("nickname") `, undefined);
        await queryRunner.query(`DROP INDEX "IDX_9a38a6b95e3425b72f164c6970"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_55fd3f0bc67773f4217ceab3fb"`, undefined);
        await queryRunner.query(`DROP TABLE "image_db_tags_tag"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_19ee4893cf3ef1eff16d3bbf05"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_312215618fce569457cdf1df1d"`, undefined);
        await queryRunner.query(`DROP TABLE "image_db_outhers_outher"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_42278d1d5983f6a927d37fff92"`, undefined);
        await queryRunner.query(`DROP TABLE "user_grant"`, undefined);
        await queryRunner.query(`DROP TABLE "refresh_token_scope"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_c31d0a2f38e6e99110df62ab0a"`, undefined);
        await queryRunner.query(`DROP TABLE "refresh_token"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_11e0cdea32bcd84e5f2f104726"`, undefined);
        await queryRunner.query(`DROP TABLE "auto_login"`, undefined);
        await queryRunner.query(`DROP TABLE "authorization_code_scope"`, undefined);
        await queryRunner.query(`DROP TABLE "authorization_code"`, undefined);
        await queryRunner.query(`DROP TABLE "redirect_uri"`, undefined);
        await queryRunner.query(`DROP TABLE "relying_party"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_065d4d8f3b5adb4a08841eae3c"`, undefined);
        await queryRunner.query(`DROP TABLE "user"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_0d4c67409aad8ab48a4a8a1279"`, undefined);
        await queryRunner.query(`DROP TABLE "outher"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_e67a107bf5046cd5b2b025a812"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_bf884fdcc2e1cd88956ea3c066"`, undefined);
        await queryRunner.query(`DROP TABLE "image"`, undefined);
        await queryRunner.query(`DROP INDEX "IDX_6a9775008add570dc3e5a0bab7"`, undefined);
        await queryRunner.query(`DROP TABLE "tag"`, undefined);
    }

}
